sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libkyotocabinet16 libkyotocabinet-dev
 - wget http://fallabs.com/kyotocabinet/javapkg/kyotocabinet-java-1.24.tar.gz
 - tar -xzf kyotocabinet-java-1.24.tar.gz
 - cd kyotocabinet-java-1.24 && ./configure --prefix=/usr && make && sudo make install && cd ..
install:
 - ./install-deps.sh ${TRAVIS_BRANCH}
 - mkdir -p target/lib && ln -s /usr/lib/libjkyotocabinet.so target/lib/libjkyotocabinet.so
